### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Amialc**
Added logout buttons, fixed issues with 04-User-profile, 05-linking-profile.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Hi @Amialc, thanks for the PR.
The #27 issue is because the package name used in the Callback Uri is obtained from the **application context**. The way to define the global package name in android is using the `application_id` property on the build.gradle file. Please rollback the changes in that commit and just update the line https://github.com/auth0-samples/auth0-android-sample/blob/master/05-Linking-Accounts/app/build.gradle#L8.
About the `logout` action I don't agree that we should handle it as Lock just delivers the `Credentials` and the user is responsible of handling them, either storing them locally or just keeping them in memory. i.e. Some of the samples include the use of SharedPreferences to store the result: `App.getInstance().getUserCredentials()`. Also pressing back closes the app and the user can open it again to retry the log in flow (as it doesn't remember you even though some samples save the credentials). If you're going to log out the user then you should clear those too..
Just remove the last commit (logout) as it doesn't make sense for the samples.

Cheers.

**Comment by Amialc** [comment]
Hi @lbalmaceda, thanks for the response.

**Comment by lbalmaceda** [comment]
@Amialc yes. I would either 1) rename it to "Clear credentials" and call `CredentialsManager.deleteCredentials()`, 2) rename the whole log out action (button+method) to something like "Log In Again" or 3) "Run Example Again" or roll back the commit. All options are ok. 👍  
Cheers!

**Comment by Amialc** [comment]
@lbalmaceda thanks for your response. I've added commits that should fix everything.

**Pull request merged**
